name: NodeJS with Webpack

on:
  pull_request:
    branches: [ "master" ]

jobs:
  permissions:
    id-token: write # This is required for requesting the JWT
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npm run build

      - name: Configure AWS credentials for Non-Prod
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::654344198836:role/qa-sign-embedded-publisher
          aws-region: us-east-1

      - name: Copy files to test locations
        run: |
          aws s3 cp umd/* s3://cdn.qa-hellosign.com/test/js/embedded/
