name: Scratch Workflow

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    permissions:
      id-token: write # This is required for requesting the JWT
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] # we should pull this from a common place

    steps:
      - uses: actions/checkout@v3

      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version package.json -r'

      - name: Embedded Beta Version
        run: 'echo "version ${{ steps.version.outputs.value }}"'
        env:
          PACKAGE_VERSION: "${{ steps.version.outputs.value }}-beta"

      - uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag: ${{ env.PACKAGE_VERSION }}

