name: Scratch Workflow

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    permissions:
      id-token: write # This is required for requesting the JWT
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] # we should pull this from a common place

    steps:
      - uses: actions/checkout@v3

      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version package.json -r'

      - name: Check existing beta releases
        uses: cardinalby/git-get-release-action@v1
        id: released
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag: "v${{ steps.version.outputs.value }}"
          doNotFailIfNotFound: true

      - name: Show me
        run: "${{ steps.released.success }}"

      - name: Block if found
        run: |
          if [[ ${{ steps.released.success }} ]];
          then
            echo "A release already exists from this version, you must bump the version to create a new beta"
            exit 1
          else 
            echo "No release for this version, generating beta package."
          fi



