name: Scratch Workflow

on:
  workflow_dispatch:

env:
  NPM_REGISTRY_URL: "https://www.npmjs.com/package/hellosign-embedded"
  BETA_SUFFIX: 'testbeta'

jobs:
  build:
    permissions:
      id-token: write # This is required for requesting the JWT
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] # we should pull this from a common place

    steps:
      - uses: actions/checkout@v3



