name: New Pull request; publish as beta package

on:
  pull_request:
    branches: [ "SPDE-130" ]

env:
  NPM_REGISTRY_URL: "https://registry.npmjs.com"
  BETA_SUFFIX: 'testbeta'
  CDN_AWS_PUBLISH_ROLE: arn:aws:iam::654344198836:role/github-actions-oidc-role-nonprod-sign-embedded
  CDN_BUCKET: cdn.staging-hellosign.com
  CDN_PATH: public/js/embedded
  AWS_REGION: us-east-1
jobs:
  build:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: write # This is required for publishing releases
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] # we should pull this from a common place

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: ${{ env.NPM_REGISTRY_URL }}

      - name: Build
        run: |
          npm install
          npm run build

      - name: Test
        run: |
          npm test

      - name: Validate Semver
        id: version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/actions-scripts/validate-release-version.js

      - name: Announce version
        run: |
          echo "v${{ steps.version.outputs.version }} is the current version."
