name: Changes approved; deploy to prod

#on:
#  merge:
#    branches: [ "master" ]

jobs:
  build:
    permissions:
      id-token: write # This is required for requesting the JWT
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] # we should pull this from a common place

    steps:
      - uses: actions/checkout@v3
